name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
        with:
          browsers: chrome:126.0
          shmSize: 2g
      - name: Check Selenoid status
        run: curl http://localhost:4444/wd/hub/status
      - name: Check application accessibility
        run: |
          curl -I https://www.croxyproxy.com/ || echo "Failed to reach croxyproxy.com"
          curl -I https://daxtra.com/support || echo "Failed to reach daxtra.com/support"
          ping -c 4 www.croxyproxy.com || echo "DNS resolution failed for croxyproxy"
          ping -c 4 daxtra.com || echo "DNS resolution failed for daxtra"
      - name: Run tests with Selenide
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub -Dheadless=true
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/reports/selenide/
            build/allure-results/
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
      - uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history